/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { useFrame, useLoader } from '@react-three/fiber';
import { AnimationMixer, Mesh } from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export default function Model() {
  // const { nodes, materials } = useGLTF('/asgv-3/Dalmore2.glb');
  const model = useLoader(GLTFLoader, '/asgv-3/dalmore2.glb');
  // const mesh = useRef<Mesh | null>(null);
  // Here's the animation part
  // *************************
  let mixer: AnimationMixer;
  //  console.log(model);
  if (model.animations.length) {
    mixer = new AnimationMixer(model.scene);
    model.animations.forEach((clip) => {
      const action = mixer.clipAction(clip);
      action.play();
    });
  }

  useFrame((state, delta) => {
    mixer?.update(delta);
  });
  // *************************

  return <primitive object={model.scene} scale={0.2} />;
}
useGLTF.preload('/asgv-3/dalmore2.glb');
