/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { Plane, Sphere, useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import video from '../../assets/GIF-1_1.mp4';
import * as THREE from 'three';

const videoElement: HTMLVideoElement = document.createElement('video');
videoElement.src = video;

const videoTexture = new THREE.VideoTexture(videoElement);
const VideoMaterial = new THREE.MeshBasicMaterial({
  side: THREE.FrontSide,
  toneMapped: false,
  // color: 'blue',
  map: videoTexture,
});

export default function Model() {
  useEffect(() => {
    // const screen = new THREE.PlaneGeometry(1.92, 1.08);
    // const videoScreen = new THREE.Mesh(screen, VideoMaterial);
    // materials.Intro.map = videoTexture;
    // materials.Intro.side = THREE.FrontSide;
  });
  return (
    <>
      <Plane args={[1.92, 1.08]} material={VideoMaterial} />
      {/* <Sphere>
        <meshBasicMaterial color="hotpink" />
      </Sphere> */}
      ;
    </>
  );
}
